kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "angular-example-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/ivid-123/demo-2"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
